[tool.poetry]
name = "atramentum-api"
version = "0.1.0"
description = "Backend API for Atramentum (AI-powered IDE for Writers)"
authors = ["devpfan <pfabian@outlook.com>"]
readme = "README.md"
packages = [{include = "app"}]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.110.0"
uvicorn = {extras = ["standard"], version = "^0.28.0"}
pydantic = "^2.6.0"
pydantic-settings = "^2.2.0"
sqlalchemy = "^2.0.28"
psycopg2-binary = "^2.9.9"
pgvector = "^0.2.5"
alembic = "^1.13.1"
google-generativeai = "^0.4.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
