"""Add book_id to CodexEntry

Revision ID: 080712b9f4f7
Revises: c68230d2e4fa
Create Date: 2026-07-30 11:08:29.787656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '080712b9f4f7'
down_revision: Union[str, Sequence[str], None] = 'c68230d2e4fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('codex_entries', sa.Column('book_id', sa.Integer(), server_default='1', nullable=False))
    op.create_index(op.f('ix_codex_entries_book_id'), 'codex_entries', ['book_id'], unique=False)
    op.create_foreign_key(None, 'codex_entries', 'books', ['book_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'codex_entries', type_='foreignkey')
    op.drop_index(op.f('ix_codex_entries_book_id'), table_name='codex_entries')
    op.drop_column('codex_entries', 'book_id')
    # ### end Alembic commands ###
