"""Add ai_settings to User

Revision ID: 17960ac60e7d
Revises: 7a0728985292
Create Date: 2026-07-30 11:34:41.839904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17960ac60e7d'
down_revision: Union[str, Sequence[str], None] = '7a0728985292'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ai_settings', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ai_settings')
    # ### end Alembic commands ###
