"""Add Codex and pgvector

Revision ID: 19c3082e0f90
Revises: b7d27c4926ea
Create Date: 2026-07-28 12:01:51.436262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '19c3082e0f90'
down_revision: Union[str, Sequence[str], None] = 'b7d27c4926ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Activar pgvector en PostgreSQL
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('codex_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('CHARACTER', 'LOCATION', 'OBJECT', 'FACTION', 'CONCEPT', name='codexcategory'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('attributes', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=768), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_codex_entries_id'), 'codex_entries', ['id'], unique=False)
    op.create_index(op.f('ix_codex_entries_name'), 'codex_entries', ['name'], unique=False)
    op.create_table('codex_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alias_name', sa.String(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['codex_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_codex_aliases_alias_name'), 'codex_aliases', ['alias_name'], unique=True)
    op.create_index(op.f('ix_codex_aliases_id'), 'codex_aliases', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_codex_aliases_id'), table_name='codex_aliases')
    op.drop_index(op.f('ix_codex_aliases_alias_name'), table_name='codex_aliases')
    op.drop_table('codex_aliases')
    op.drop_index(op.f('ix_codex_entries_name'), table_name='codex_entries')
    op.drop_index(op.f('ix_codex_entries_id'), table_name='codex_entries')
    op.drop_table('codex_entries')
    # ### end Alembic commands ###
