"""add scene chunks

Revision ID: 22f218d396f8
Revises: 4ba6a7d5745d
Create Date: 2026-07-30 20:17:49.787024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '22f218d396f8'
down_revision: Union[str, Sequence[str], None] = '4ba6a7d5745d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scene_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scene_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=768), nullable=True),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scene_chunks_id'), 'scene_chunks', ['id'], unique=False)
    op.create_index(op.f('ix_scene_chunks_scene_id'), 'scene_chunks', ['scene_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scene_chunks_scene_id'), table_name='scene_chunks')
    op.drop_index(op.f('ix_scene_chunks_id'), table_name='scene_chunks')
    op.drop_table('scene_chunks')
    # ### end Alembic commands ###
