"""Add series support to codex

Revision ID: 4ba6a7d5745d
Revises: 17960ac60e7d
Create Date: 2026-07-30 17:45:16.621099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ba6a7d5745d'
down_revision: Union[str, Sequence[str], None] = '17960ac60e7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('codex_entries', sa.Column('series_id', sa.Integer(), nullable=True))
    op.alter_column('codex_entries', 'book_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.create_index(op.f('ix_codex_entries_series_id'), 'codex_entries', ['series_id'], unique=False)
    op.create_foreign_key(None, 'codex_entries', 'series', ['series_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'codex_entries', type_='foreignkey')
    op.drop_index(op.f('ix_codex_entries_series_id'), table_name='codex_entries')
    op.alter_column('codex_entries', 'book_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.drop_column('codex_entries', 'series_id')
    # ### end Alembic commands ###
