"""add_admin_roles_and_settings

Revision ID: 6808a6d94e3a
Revises: 22f218d396f8
Create Date: 2026-07-31 11:15:16.641586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6808a6d94e3a'
down_revision: Union[str, Sequence[str], None] = '22f218d396f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_global_settings_key'), 'global_settings', ['key'], unique=False)
    op.add_column('users', sa.Column('is_superuser', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_superuser')
    op.drop_index(op.f('ix_global_settings_key'), table_name='global_settings')
    op.drop_table('global_settings')
    # ### end Alembic commands ###
