"""Add previous_titles to Book

Revision ID: 7a0728985292
Revises: 080712b9f4f7
Create Date: 2026-07-30 11:22:20.531040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a0728985292'
down_revision: Union[str, Sequence[str], None] = '080712b9f4f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('previous_titles', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'previous_titles')
    # ### end Alembic commands ###
