"""add_project_type_to_books

Revision ID: 869ccfc39881
Revises: f284bcd48045
Create Date: 2026-08-03 08:50:42.190166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '869ccfc39881'
down_revision: Union[str, Sequence[str], None] = 'f284bcd48045'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('project_type', sa.String(), server_default='novel', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'project_type')
    # ### end Alembic commands ###
