"""Change attributes to JSONB

Revision ID: ba58f2cdf4cf
Revises: ac603494fe30
Create Date: 2026-07-29 16:44:53.317039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ba58f2cdf4cf'
down_revision: Union[str, Sequence[str], None] = 'ac603494fe30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('codex_entries', 'attributes')
    op.add_column('codex_entries', sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('codex_entries', 'attributes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
