"""add_image_url_to_codex

Revision ID: f284bcd48045
Revises: 6808a6d94e3a
Create Date: 2026-07-31 16:16:41.707119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f284bcd48045'
down_revision: Union[str, Sequence[str], None] = '6808a6d94e3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('codex_entries', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('codex_entries', 'image_url')
    # ### end Alembic commands ###
